v2.11.1
nanos-world/nanos-world-sandbox pull request #7
Opened 2022-05-13 18:31 UTC by vugi99

- Add Lock Time Of The Day checkbox in context menu
- Remove clientside persistent data code (unused)
- Add respawn key (Y by default)

2022-05-18 09:12 UTC, gtnardy requested changes
Thank you for the PR!

What do you think of moving the respawn to a button in the Context menu? I didn't want people accidentally hitting Y and respawning in the middle of something

2022-05-18 13:45 UTC, vugi99 commented
It was the main idea but i am not good at css but i'll try if you want

2022-05-18 14:18 UTC, vugi99 commented
Changes done

2022-05-22 13:13 UTC, gtnardy approved these changes

2022-05-22 13:13 UTC, gtnardy commented on Package.toml
> +    version =              "2.11.1"
```suggestion
    version =              "2.11.2"
```

2022-05-22 13:15 UTC, merged